name: Attach Release Artifacts

on: 
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: create artifacts directory
        run: mkdir artifacts
        working-directory: ./

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts
    
    
        
    
      