- name: build
run: make build
  - name: version
    run: echo "::set-output name=version::$(https://github.com/unicorn-engine/unicorn/archive/refs/tags/ --version)"
    id: version
  - name: release
    uses: actions/create-release@v3
    id: create_release
    with:
      draft: false
      prerelease: false
      release_name: ${{ steps.version.outputs.version }}
      tag_name: ${{ github.ref }}
      body_path: ChangeLog

